name: main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create target directory
        run: mkdir target
      - name: CMake
        run: cmake -DCMAKE_BUILD_TYPE=Release ..
        working-directory: target
      - name: Build
        run: cmake --build .
